tasks:
  - task: shell.docker.Ensure
    name: ubuntu
    image: algorand/indexer-ci-linux
    version: latest
    dockerFilePath: docker/Dockerfile.mule

  - task: docker.Make
    name: deploy-deb
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: mule-deploy-deb WORKDIR=/projects/indexer

jobs:
  deploy:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.deploy-deb

